FROM dunglas/frankenphp:php8.3-bookworm

WORKDIR /app

RUN install-php-extensions \
    intl \
    opcache \
    pdo_mysql \
    pdo_pgsql \
    zip

COPY . .

RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer

RUN composer install \
    --no-dev \
    --no-interaction \
    --no-progress \
    --prefer-dist \
    --optimize-autoloader

RUN mkdir -p var/cache var/log \
    && chown -R www-data:www-data var \
    && php bin/console cache:clear --env=prod --no-debug

COPY Caddyfile /etc/caddy/Caddyfile

ENV APP_ENV=prod
ENV APP_DEBUG=0

EXPOSE 8080

CMD ["sh", "-c", "frankenphp run --config /etc/caddy/Caddyfile --adapter caddyfile"]